# This workflow will build a container using Docker and then publish it to docker hub

name: Docker Publish

on:
  push:
    branches:
    - main
    - develop

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  DOCKERHUB_USERNAME: lukecmstevens

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Build with Maven
      run: mvn -B package -s .m2/settings.xml --file pom.xml

    - name: Get version
      run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "MVN_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Get artifactId
      run: |
          ARTIFACT=$( mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout )
          echo "MVN_ARTIFACT=$ARTIFACT" >> $GITHUB_ENV

    - name: Get groupId
      run: |
          GROUP=$( mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout )
          echo "MVN_GROUP=$GROUP" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false # Don't push until certain it works
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.MVN_ARTIFACT }}:${{ env.MVN_VERSION }}
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.MVN_ARTIFACT }}:latest
        build-args: |
          NAME=${{ env.MVN_ARTIFACT }}
          GROUP=${{ env.MVN_GROUP }}
          VERSION=${{ env.MVN_VERSION }}
