# This workflow will build a container using Docker and then publish it to docker hub

name: Docker Publish

on:
  push:
    branches:
    - master
    - develop

env:
  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  DOCKERHUB_USERNAME: lukecmstevens

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Build with Maven
      run: mvn -B package -s .m2/settings.xml --file pom.xml

    - name: Export maven properties
      run: ./mvn-export.sh

    - name: Echo image name
      run: echo $DOCKERHUB_USERNAME/$MVN_ARTIFACT:$MVN_VERSION

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
