# This workflow does all the tagging, building, publishing etc. around a new release

name: release

on:
  push:
    branches:
    - main

env:
  DOCKERHUB_USERNAME: lukecmstevens

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    # Finalise the version by removing the -beta or -SNAPSHOT suffix if it exists

    - name: Finalise version
      uses: lukecmstevens/actions/finalise-version@v1

    # Build maven package (including running tests)

    - name: Build with Maven
      uses: lukecmstevens/actions/maven-task@v1
      with:
        task: package
        token: ${{ secrets.GITHUB_TOKEN }}

    # Get maven properties and store in environment

    - name: Get maven properties
      uses: lukecmstevens/actions/get-mvn-properties@v1

    # Setup for docker build and push

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push docker artifact to repo
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true # Don't push until certain it works
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.MVN_ARTIFACT }}:${{ env.MVN_VERSION }}
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.MVN_ARTIFACT }}:latest
        build-args: |
          NAME=${{ env.MVN_ARTIFACT }}
          GROUP=${{ env.MVN_GROUP }}
          VERSION=${{ env.MVN_VERSION }}

    # We finalised the version earlier, now committing, tagging, and pushing to main

    - name: Commit and tag version update
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        commit_message: Release version ${{ env.MVN_VERSION }}
        tagging_message: ${{ env.MVN_VERSION }}

    # Create a release and upload the jar to it

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.MVN_VERSION }}
        release_name: Release ${{ env.MVN_VERSION }}
        body_path: changelog.md

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/Application.jar
        asset_name: ${{ env.MVN_ARTIFACT }}-${{ env.MVN_VERSION }}.jar
        asset_content_type: application/java-archive

    # Switch to develop, bump version and commit

    - name: Switch to develop
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Bump version
      uses: lukecmstevens/actions/bump-version@v1
      with:
       version-suffix: beta

    - name: Commit and push bumped version
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: develop
        commit_message: Bump version

        
