# This workflow does all the tagging, building, publishing etc. around a new release

name: release

on:
  push:
    branches:
      - main

env:
  GH_USER: lukecmstevens
  DOCKERHUB_USERNAME: lukecmstevens

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Finalise version
        run: ./gradlew finaliseVersion

      - name: Write project properties to env file
        run: ./gradlew exportProperties

      # Setup for docker build and push

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Push docker artifact to repo

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true # Don't push until certain it works
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.PROJECT_NAME }}:latest
          build-args: |
            GH_USER=${{ env.GH_USER }}
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
            PROJECT_NAME=${{ env.PROJECT_NAME }}
            PROJECT_VERSION=${{ env.PROJECT_VERSION }}

      # We finalised the version earlier, now committing, tagging, and pushing to main

      - name: Commit and tag version update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Release version ${{ env.PROJECT_VERSION }}
          tagging_message: ${{ env.PROJECT_VERSION }}

      # Create a release and upload the jar to it

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PROJECT_VERSION }}
          release_name: Release ${{ env.PROJECT_VERSION }}
          body_path: changelog.md

      # Switch to develop, bump version and commit

      - name: Switch to develop
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Bump version
        run: ./gradlew bumpVersion

      - name: Commit and push bumped version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: develop
          commit_message: Bump version
